import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { TooltipProvider } from "@/components/ui/tooltip";
// import { Header } from "@/components/Layout/Header";
import { Footer } from "@/components/Layout/Footer";
import { WhatsAppFloat } from "@/components/Layout/WhatsAppFloat";
import { MobileCartBar } from "@/components/Layout/MobileCartBar";
import { AuthProvider } from "@/context/AuthContext";
import { GlobalHeader } from "@/components/Layout/GlobalHeader";

const inter = Inter({subsets:['latin'],variable:'--font-sans'});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", geistSans.variable, geistMono.variable, "font-sans", inter.variable)}
    >
        <body className="min-h-full flex flex-col">
          <TooltipProvider>
            <AuthProvider user={null}>              
              <div className="flex min-h-screen flex-col bg-soft-pink">
                <GlobalHeader />
                <main className="flex-1">{children}</main>
                <Footer />
                <WhatsAppFloat />
                <MobileCartBar />
              </div>
          </AuthProvider>
        </TooltipProvider>
      </body>
    </html>
  );
}
